In [1]:
!pip install google-cloud-storage

Requirement already satisfied: google-cloud-storage in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (1.36.1)
Requirement already satisfied: google-auth<2.0dev,>=1.11.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-cloud-storage) (1.27.0)
Requirement already satisfied: google-resumable-media<2.0dev,>=1.2.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-cloud-storage) (1.2.0)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-cloud-storage) (1.6.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-cloud-storage) (2.25.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (0.2.8)
Requirement already satisfied: setuptools>=40.3.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (52.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (4.2.1)
Requirement already satisfied: six>=1.9.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (1.15.0)
Requirement already satisfied: google-api-core<2.0.0dev,>=1.21.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (1.26.0)
Requirement already satisfied: protobuf>=3.12.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-api-core<2.0.0dev,>=1.21.0->google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (3.15.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-api-core<2.0.0dev,>=1.21.0->google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (1.53.0)
Requirement already satisfied: packaging>=14.3 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-api-core<2.0.0dev,>=1.21.0->google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (20.9)
Requirement already satisfied: pytz in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-api-core<2.0.0dev,>=1.21.0->google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (2021.1)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage) (1.1.2)
Requirement already satisfied: cffi>=1.0.0 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage) (1.14.5)
Requirement already satisfied: pycparser in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage) (2.20)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from packaging>=14.3->google-api-core<2.0.0dev,>=1.21.0->google-cloud-core<2.0dev,>=1.4.1->google-cloud-storage) (2.4.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.11.0->google-cloud-storage) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mickaelkomendyak/.pyenv/versions/3.8.6/envs/galaxy_project/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2020.12.5)

In [2]:
import pandas as pd
from google.cloud import storage

In [3]:
BUCKET_DATA_PATH = "gs://lw-verspieren-starwars/data/"

In [4]:
def rename(GalaxyID):
    return str(GalaxyID)+'.jpg'

In [5]:
def get_data(y, nrows): # add nrows to sample
    '''returns a DataFrame with nrows from s3 bucket'''
    
    if y == 'train':
        # Loading DataFrames
        df_y = pd.read_csv(f'{BUCKET_DATA_PATH}training_solutions_rev1.csv', nrows=nrows)
        df_images =  pd.read_csv(f'{BUCKET_DATA_PATH}images_liste_train.csv', nrows=nrows)
        
        # Checking images corresponds to df
        list_images = list(df_images['0'])
        df_Galaxy_ID = pd.DataFrame([list_images[i].replace('.jpg','') for i in range(len(list_images))]).rename(columns={0:'GalaxyID'}).astype('int64')
        df = df_y.merge(df_Galaxy_ID, on='GalaxyID', how='inner')
        
        # Preparing df
        df['image'] = df_images['0']
        df_data = df.drop(columns=['GalaxyID'])
        
        return df_data

    if y == 'test':
        # Loading DataFrame
        df_y = pd.read_csv(f'{BUCKET_DATA_PATH}central_pixel_benchmark.csv', nrows=nrows)
        
        # Preparing df
        df_y['image'] = df_y['GalaxyID'].apply(rename)
        df_data = df_y.drop(columns=['GalaxyID'])
        
        return df_data
    return print("Please provide 'train' or 'test' ")

In [6]:
get_data('test', 4)

,Class1.1,Class1.2,Class1.3,Class2.1,Class2.2,Class3.1,Class3.2,Class4.1,Class4.2,Class5.1,...,Class10.1,Class10.2,Class10.3,Class11.1,Class11.2,Class11.3,Class11.4,Class11.5,Class11.6,image
0,0.468481,0.506185,0.025334,0.099844,0.406341,0.095167,0.311174,0.185080,0.221262,0.019015,...,0.082314,0.071253,0.031512,0.012281,0.079964,0.014346,0.006369,0.006649,0,100018.jpg
1,0.468481,0.506185,0.025334,0.099844,0.406341,0.095167,0.311174,0.185080,0.221262,0.019015,...,0.082314,0.071253,0.031512,0.012281,0.079964,0.014346,0.006369,0.006649,0,100037.jpg
2,0.408863,0.550817,0.040320,0.085001,0.465816,0.117082,0.348734,0.225783,0.240033,0.184419,...,0.068422,0.087200,0.070161,0.028580,0.094907,0.017221,0.007030,0.004902,0,100042.jpg
3,0.322002,0.657280,0.020718,0.136922,0.520358,0.121784,0.398573,0.310370,0.209988,0.071409,...,0.128488,0.123550,0.058332,0.021707,0.140455,0.028082,0.011659,0.008495,0,100052.jpg

In [7]:
def get_full_data():
    '''returns a DataFrame with all data'''
    # Loading train
    df_y = pd.read_csv(f'{BUCKET_DATA_PATH}training_solutions_rev1.csv')
    df_images =  pd.read_csv(f'{BUCKET_DATA_PATH}images_liste_train.csv')
    
    # Checking images corresponds to df
    list_images = list(df_images['0'])
    df_Galaxy_ID = pd.DataFrame([list_images[i].replace('.jpg','') for i in range(len(list_images))]).rename(columns={0:'GalaxyID'}).astype('int64')
    df_train = df_y.merge(df_Galaxy_ID, on='GalaxyID', how='inner')
    
    # Loading train
    df_test = pd.read_csv(f'{BUCKET_DATA_PATH}central_pixel_benchmark.csv')
    return {'train':df_train, 'test':df_test}

In [8]:
full_data = get_full_data()

In [9]:
full_data['train'].head()

,GalaxyID,Class1.1,Class1.2,Class1.3,Class2.1,Class2.2,Class3.1,Class3.2,Class4.1,Class4.2,...,Class9.3,Class10.1,Class10.2,Class10.3,Class11.1,Class11.2,Class11.3,Class11.4,Class11.5,Class11.6
0,100008,0.383147,0.616853,0.000000,0.000000,0.616853,0.038452,0.578401,0.418398,0.198455,...,0.000000,0.279952,0.138445,0.000000,0.000000,0.092886,0.0,0.0,0.0,0.325512
1,100023,0.327001,0.663777,0.009222,0.031178,0.632599,0.467370,0.165229,0.591328,0.041271,...,0.018764,0.000000,0.131378,0.459950,0.000000,0.591328,0.0,0.0,0.0,0.000000
2,100053,0.765717,0.177352,0.056931,0.000000,0.177352,0.000000,0.177352,0.000000,0.177352,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000
3,100078,0.693377,0.238564,0.068059,0.000000,0.238564,0.109493,0.129071,0.189098,0.049466,...,0.000000,0.094549,0.000000,0.094549,0.189098,0.000000,0.0,0.0,0.0,0.000000
4,100090,0.933839,0.000000,0.066161,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000

In [10]:
df_y = pd.read_csv(f'{BUCKET_DATA_PATH}central_pixel_benchmark.csv', nrows=4)

In [11]:
def rename(GalaxyID):
    return str(GalaxyID)+'.jpg'

In [12]:
rename(112)

'112.jpg'

In [13]:
df.head(2)

NameError: name 'df' is not defined

In [ ]:
df['image'] = df_images['0']
df_X_y = df.drop(columns=['GalaxyID'])

In [ ]:
df_X_y